### ISSUE TITLE
calc_zipval.py

### ISSUE THREAD

**Issue by drkoryjohns** [tangwei1129/virscan#1]
Hello,

I am encountering the below error when attempting to generate p-values form the counts file:

module load python/3.7 && python bin/calc_zipval.py count/VC03_IDX192_S192.count.csv.gz count/INPUT.count.csv.gz log > pvalues/VC03_IDX192_S192.zipval.csv

Traceback (most recent call last):
  File "bin/calc_zipval.py", line 133, in <module>
    pvals = calc_pvals(in_, out, zigp, param_models)
  File "bin/calc_zipval.py", line 101, in calc_pvals
    params_fits = fit_models(in_, out, model)
  File "bin/calc_zipval.py", line 22, in fit_models
    grouped = filtered.groupby(in_.ix[filtered.index])
  File "/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'ix'

Is there a coding update to the calc_zpal.py script needed due to deprecation of functions calls?

My INPUT.counts.csv.gz file head looks as follows:

id,INPUT
tile1,600
tile2,620
tile3,330
tile4,235
tile5,1732
tile6,1268
tile7,960
tile8,232
tile9,7

My sample file hear looks as follows:

id,SAMPLE_ID
tile1,51
tile2,36
tile3,18
tile4,3
tile5,110
tile6,75
tile7,40
tile8,8
tile9,0

My bin dir has the following saved therein:

calc_zipval.py
generalizedpoisson.py
zigp.py

Thanks ... best,

Kory Johnson

**Comment by tangwei1129** [comment]
Hi 
Pls ask Xin Wang from NCI to get updated code.
Thx
Wei
